Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
